# User Settings | Edit these according to your site

title: David N. Wright
email: davidnwright@outlook.com
author: David N. Wright

description: > # this means to ignore newlines until "baseurl:"
  Chaplin is a minimalistic, mobile friendly theme for Jekyll. Used by Dave.
  The Documentation for it is available on this website itself. 
  You can check out the source on <a href="http://github.com/bk2dcradle/Chaplin" class="deactivate-link"><span> GitHub </span></a>

url: "http://davidnwright.github.io/" # the base hostname & protocol for your site
baseurl: "/borderland" # the subpath of your site, e.g. /blog
twitter_username: davidnwright
github_username:  davidnwright

permalink:          /:year/:month/:day/:title.html

paginate: 5
paginate_path: "/page/:num"
comments: true

heading_font: Lobster 
about_footer: true
short_bio: >
    I'm someone who likes to think big and do little. But every once and awhile, I come up with something... 
profile_picture: 

google_analytics: true
tracking_id: # Your google analytics tracking id

# Build settings | Do not edit anything below this
markdown: kramdown

gems:
  - jekyll-paginate

sass:
  style:            compressed
  sass_dir:         _sass

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
